# Generated by Django 5.0.1 on 2024-01-27 22:03

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_email', hash_key='84ef13ba3a0f34e08fdb782f08da11680395c0c3dcc52a558e723629d32fcc27', help_text='内容によっては私たちからお問い合わせ内容について連絡させて頂きます', max_length=66, null=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry_text',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_inquiry_text', hash_key='84ef13ba3a0f34e08fdb782f08da11680395c0c3dcc52a558e723629d32fcc27', max_length=66, null=True, verbose_name='問い合わせ内容'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='ip_address',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_ip_address', hash_key='84ef13ba3a0f34e08fdb782f08da11680395c0c3dcc52a558e723629d32fcc27', max_length=66, null=True, verbose_name='照会者IPアドレス'),
        ),
    ]
