# Generated by Django 5.0.1 on 2024-01-27 22:16

import apps.inquiry.models.Inquiry_models
import django.db.models.deletion
import django.utils.timezone
import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_alter_inquiry_email_alter_inquiry_inquiry_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name': '問い合わせ一覧', 'verbose_name_plural': '問い合わせ一覧'},
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='_email',
            field=encrypted_fields.fields.EncryptedEmailField(max_length=255, verbose_name='メールアドレス(Encrypted:Form使用不可)'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='_inquiry_text',
            field=apps.inquiry.models.Inquiry_models.EncryptedTextField(max_length=2000, verbose_name='問い合わせ内容(Encrypted:Form使用不可)'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='_ip_address',
            field=apps.inquiry.models.Inquiry_models.EncryptedIPAddressField(blank=True, null=True, verbose_name='照会者IPアドレス(Encrypted:Form使用不可)'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='date_complete',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='対応完了日時'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='問い合わせ日時'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='situation',
            field=models.IntegerField(choices=[(0, '未対応'), (11, '状況調査中'), (12, '照会者への確認中'), (13, '関係者への確認中'), (80, 'その他対応中'), (90, '完了')], default=0, verbose_name='対応状況'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='unique_account_id',
            field=models.ForeignKey(blank=True, db_index=False, help_text='紐づくアカウントID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_inquiry_unique_account_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
