# Generated by Django 5.0.1 on 2024-01-27 22:20

import apps.inquiry.models.Inquiry_models
import django.db.models.deletion
import django.utils.timezone
import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0003_alter_inquiry_options_alter_inquiry__email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name': 'Inquiry List', 'verbose_name_plural': 'Inquiry List'},
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='_email',
            field=encrypted_fields.fields.EncryptedEmailField(max_length=255, verbose_name='Email Address (Encrypted: Not for form use)'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='_inquiry_text',
            field=apps.inquiry.models.Inquiry_models.EncryptedTextField(max_length=2000, verbose_name='Inquiry Text (Encrypted: Not for form use)'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='_ip_address',
            field=apps.inquiry.models.Inquiry_models.EncryptedIPAddressField(blank=True, null=True, verbose_name='Inquirer IP Address (Encrypted: Not for form use)'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='date_complete',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Completion Date and Time'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inquiry Date and Time'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_email', hash_key='84ef13ba3a0f34e08fdb782f08da11680395c0c3dcc52a558e723629d32fcc27', help_text='Depending on the content, we may contact you regarding the inquiry', max_length=66, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry_text',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_inquiry_text', hash_key='84ef13ba3a0f34e08fdb782f08da11680395c0c3dcc52a558e723629d32fcc27', max_length=66, null=True, verbose_name='Inquiry Text'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='ip_address',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_ip_address', hash_key='84ef13ba3a0f34e08fdb782f08da11680395c0c3dcc52a558e723629d32fcc27', max_length=66, null=True, verbose_name='Inquirer IP Address'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='situation',
            field=models.IntegerField(choices=[(0, '未対応'), (11, '状況調査中'), (12, '照会者への確認中'), (13, '関係者への確認中'), (80, 'その他対応中'), (90, '完了')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='unique_account_id',
            field=models.ForeignKey(blank=True, db_index=False, help_text='Associated Account ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_inquiry_unique_account_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
