# Generated by Django 5.0.1 on 2024-01-27 22:03

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersocialauth',
            name='extra_data',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_extra_data', hash_key='84ef13ba3a0f34e08fdb782f08da11680395c0c3dcc52a558e723629d32fcc27', max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='usersocialauth',
            name='uid',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_uid', hash_key='84ef13ba3a0f34e08fdb782f08da11680395c0c3dcc52a558e723629d32fcc27', max_length=66, null=True),
        ),
    ]
