# Generated by Django 5.0.1 on 2024-01-27 22:03

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessattempt',
            name='get_data',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_get_data', hash_key='84ef13ba3a0f34e08fdb782f08da11680395c0c3dcc52a558e723629d32fcc27', max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='accessattempt',
            name='http_accept',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_http_accept', hash_key='84ef13ba3a0f34e08fdb782f08da11680395c0c3dcc52a558e723629d32fcc27', max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='accessattempt',
            name='ip_address',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_ip_address', hash_key='84ef13ba3a0f34e08fdb782f08da11680395c0c3dcc52a558e723629d32fcc27', max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='accessattempt',
            name='path_info',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_path_info', hash_key='84ef13ba3a0f34e08fdb782f08da11680395c0c3dcc52a558e723629d32fcc27', max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='accessattempt',
            name='post_data',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_get_data', hash_key='84ef13ba3a0f34e08fdb782f08da11680395c0c3dcc52a558e723629d32fcc27', max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='accessattempt',
            name='user_agent',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_user_agent', hash_key='84ef13ba3a0f34e08fdb782f08da11680395c0c3dcc52a558e723629d32fcc27', max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='accessattempt',
            name='username',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_username', hash_key='84ef13ba3a0f34e08fdb782f08da11680395c0c3dcc52a558e723629d32fcc27', max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='accessfailurelog',
            name='http_accept',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_http_accept', hash_key='84ef13ba3a0f34e08fdb782f08da11680395c0c3dcc52a558e723629d32fcc27', max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='accessfailurelog',
            name='ip_address',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_ip_address', hash_key='84ef13ba3a0f34e08fdb782f08da11680395c0c3dcc52a558e723629d32fcc27', max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='accessfailurelog',
            name='path_info',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_path_info', hash_key='84ef13ba3a0f34e08fdb782f08da11680395c0c3dcc52a558e723629d32fcc27', max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='accessfailurelog',
            name='user_agent',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_user_agent', hash_key='84ef13ba3a0f34e08fdb782f08da11680395c0c3dcc52a558e723629d32fcc27', max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='accessfailurelog',
            name='username',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_username', hash_key='84ef13ba3a0f34e08fdb782f08da11680395c0c3dcc52a558e723629d32fcc27', max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='http_accept',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_http_accept', hash_key='84ef13ba3a0f34e08fdb782f08da11680395c0c3dcc52a558e723629d32fcc27', max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='ip_address',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_ip_address', hash_key='84ef13ba3a0f34e08fdb782f08da11680395c0c3dcc52a558e723629d32fcc27', max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='path_info',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_path_info', hash_key='84ef13ba3a0f34e08fdb782f08da11680395c0c3dcc52a558e723629d32fcc27', max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='user_agent',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_user_agent', hash_key='84ef13ba3a0f34e08fdb782f08da11680395c0c3dcc52a558e723629d32fcc27', max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='username',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_username', hash_key='84ef13ba3a0f34e08fdb782f08da11680395c0c3dcc52a558e723629d32fcc27', max_length=66, null=True),
        ),
    ]
