# Generated by Django 4.2.1 on 2024-01-25 16:35

import accounts.models.CustomUser_models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import encrypted_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('unique_account_id', models.SlugField(default='e8dde7582b6847ef8a1f03c70dde2bf5', error_messages={'unique': 'This account name is already in use'}, help_text='Alphabet, numbers, underscore, hyphen 32 characters or less', unique=True, verbose_name='Account name (No Japanese)')),
                ('_email', encrypted_fields.fields.EncryptedEmailField(max_length=255, verbose_name='Email address (Encrypted:Form not usable)')),
                ('email', encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_email', error_messages={'unique': 'This email address is already in use'}, hash_key='***YOUR_ENCRYPTION_HASH_KEY***', help_text='Email address (Unique, 255 characters or less)', max_length=66, null=True, unique=True, verbose_name='Email address')),
                ('change_email', encrypted_fields.fields.EncryptedEmailField(default='dummy@mail.com', max_length=255, verbose_name='Email address to be changed (Encrypted:Form not usable)')),
                ('is_change_email_request', models.BooleanField(default=False, verbose_name='Email reset request in progress')),
                ('is_social_login', models.BooleanField(default=False, verbose_name='Social login')),
                ('is_set_password', models.BooleanField(default=True, verbose_name='Password set status')),
                ('is_active', models.BooleanField(default=True, help_text='If disabled, login will not be possible', verbose_name='Account is active')),
                ('is_staff', models.BooleanField(default=False, help_text='IT staff authority (Usually do not check)', verbose_name='IT staff')),
                ('is_superuser', models.BooleanField(default=False, help_text='IT administrator authority (Usually do not check)', verbose_name='IT administrator')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date and time', verbose_name='Creation date and time')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '01_User Information',
                'verbose_name_plural': '01_User Information',
                'db_table': 'custom_user_model',
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.CustomUser_models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivateToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_token', encrypted_fields.fields.EncryptedTextField(default='d260e34d002d42ebb7bcef3756c2b332', verbose_name='Token (Encrypted:Form not usable)')),
                ('token', encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_token', hash_key='***YOUR_ENCRYPTION_HASH_KEY***', max_length=66, null=True, unique=True, verbose_name='Token')),
                ('expired_at', models.DateTimeField(default=datetime.datetime(2024, 1, 26, 2, 35, 16, 805525))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_activate_tokens_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivateToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_token', encrypted_fields.fields.EncryptedTextField(default='d260e34d002d42ebb7bcef3756c2b332', verbose_name='Token(Encrypted:Form使用不可)')),
                ('token', encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_token', hash_key='***YOUR_ENCRYPTION_HASH_KEY***', max_length=66, null=True, unique=True, verbose_name='Token')),
                ('expired_at', models.DateTimeField(default=datetime.datetime(2024, 1, 26, 2, 35, 16, 805525))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_activate_tokens_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '02_Issue Authentication Token',
                'verbose_name_plural': '02_Issue Authentication Tokens',
                'db_table': 'activate_token_model',
            },
        ),
    ]
