# Generated by Django 4.2.1 on 2024-01-25 16:35

import datetime
from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activatetoken',
            name='_token',
            field=encrypted_fields.fields.EncryptedTextField(default='71b7404719b840f0b5aa097f03687430', verbose_name='Token(Encrypted:Form使用不可)'),
        ),
        migrations.AlterField(
            model_name='activatetoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 2, 35, 18, 103391)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unique_account_id',
            field=models.SlugField(default='45a369b0c57f4d2098e2f3f70cd6a38d', error_messages={'unique': 'このアカウント名は既に利用されています'}, help_text='アルファベット、数字、アンダーバー、ハイフン 32文字以下', unique=True, verbose_name='アカウント名(日本語不可)'),
        ),
    ]
