# Generated by Django 4.2.1 on 2024-01-25 16:35

import datetime
from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_activatetoken__token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activatetoken',
            name='_token',
            field=encrypted_fields.fields.EncryptedTextField(default='753c6c5264e540c6a0949b77980d6e52', verbose_name='Token (Encrypted: Form not usable)'),
        ),
        migrations.AlterField(
            model_name='activatetoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 2, 35, 21, 740542)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unique_account_id',
            field=models.SlugField(default='93f292eede3d48b7bda3a7def134142e', error_messages={'unique': 'This account name is already in use'}, help_text='Alphabet, numbers, underscore, hyphen 32 characters or less', unique=True, verbose_name='Account name (No Japanese)'),
        ),
]