# Generated by Django 4.2.1 on 2024-01-25 16:35

import apps.access_security.models.AccessSecurity_models
import apps.access_security.models.BlockIpList_models
from django.db import migrations, models
import django.utils.timezone
import encrypted_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_ip', apps.access_security.models.AccessSecurity_models.EncryptedIPAddressField(blank=True, null=True, verbose_name='ip')),
                ('ip', encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_ip', hash_key='***YOUR_ENCRYPTION_HASH_KEY***', max_length=66, null=True)),
                ('type', models.CharField(blank=True, max_length=256, null=True, verbose_name='type')),
                ('request_host_url', apps.access_security.models.AccessSecurity_models.EncryptedTextField(blank=True, null=True, verbose_name='request_host_url')),
                ('request_url', apps.access_security.models.AccessSecurity_models.EncryptedTextField(blank=True, null=True, verbose_name='request_url')),
                ('user_agent', apps.access_security.models.AccessSecurity_models.EncryptedTextField(blank=True, null=True, verbose_name='user_agent')),
                ('csrf_token', apps.access_security.models.AccessSecurity_models.EncryptedTextField(blank=True, null=True, verbose_name='csrf_token')),
                ('time_zone', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=256, null=True, verbose_name='time_zone')),
                ('date_create', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='記録日時')),
            ],
            options={
                'verbose_name': '02_ブロックログ',
                'verbose_name_plural': '02_ブロックログ',
                'db_table': 'access_security_model',
            },
        ),
        migrations.CreateModel(
            name='BlockIpList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', apps.access_security.models.BlockIpList_models.EncryptedIPAddressField(verbose_name='ブロックするip')),
                ('reason', apps.access_security.models.BlockIpList_models.EncryptedTextField(blank=True, null=True, verbose_name='ブロック理由')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
            ],
            options={
                'verbose_name': '01_ブロックリスト',
                'verbose_name_plural': '01_ブロックリスト',
                'db_table': 'block_ip_list_model',
            },
        ),
    ]
