# Generated by Django 5.0.1 on 2024-01-27 22:28

import apps.access_security.models.BlockIpList_models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_security', '0002_alter_accesssecurity_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockiplist',
            options={'verbose_name': '01_Block List', 'verbose_name_plural': '01_Block List'},
        ),
        migrations.AlterField(
            model_name='blockiplist',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registration Date and Time'),
        ),
        migrations.AlterField(
            model_name='blockiplist',
            name='ip',
            field=apps.access_security.models.BlockIpList_models.EncryptedIPAddressField(verbose_name='Blocked IP Address'),
        ),
        migrations.AlterField(
            model_name='blockiplist',
            name='reason',
            field=apps.access_security.models.BlockIpList_models.EncryptedTextField(blank=True, null=True, verbose_name='Block Reason'),
        ),
    ]
