# Generated by Django 5.0.1 on 2024-01-27 22:29

import apps.access_security.models.AccessSecurity_models
import django.utils.timezone
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_security', '0003_alter_blockiplist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesssecurity',
            options={'verbose_name': '02_Block Logs', 'verbose_name_plural': '02_Block Logs'},
        ),
        migrations.AlterField(
            model_name='accesssecurity',
            name='_ip',
            field=apps.access_security.models.AccessSecurity_models.EncryptedIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='accesssecurity',
            name='csrf_token',
            field=apps.access_security.models.AccessSecurity_models.EncryptedTextField(blank=True, null=True, verbose_name='CSRF Token'),
        ),
        migrations.AlterField(
            model_name='accesssecurity',
            name='date_create',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='accesssecurity',
            name='request_host_url',
            field=apps.access_security.models.AccessSecurity_models.EncryptedTextField(blank=True, null=True, verbose_name='Request Host URL'),
        ),
        migrations.AlterField(
            model_name='accesssecurity',
            name='request_url',
            field=apps.access_security.models.AccessSecurity_models.EncryptedTextField(blank=True, null=True, verbose_name='Request URL'),
        ),
        migrations.AlterField(
            model_name='accesssecurity',
            name='time_zone',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=256, null=True, verbose_name='Time Zone'),
        ),
        migrations.AlterField(
            model_name='accesssecurity',
            name='type',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='accesssecurity',
            name='user_agent',
            field=apps.access_security.models.AccessSecurity_models.EncryptedTextField(blank=True, null=True, verbose_name='User Agent'),
        ),
    ]
