# Generated by Django 4.2.10 on 2024-02-09 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strip_customer_id', models.CharField(help_text='Customer Id of a Stripe user', max_length=300)),
                ('stripe_subscription_id', models.CharField(help_text='Subscription id of user', max_length=300)),
                ('date_create', models.DateTimeField(auto_now_add=True, help_text='Creation Date and Time', verbose_name='Creation Date and Time')),
                ('user', models.OneToOneField(help_text='User for Stripe Checkout', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
