# Generated by Django 4.2.10 on 2024-02-11 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0002_rename_strip_customer_id_stripecustomer_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0)),
                ('is_free', models.BooleanField(default=False)),
                ('limit', models.PositiveIntegerField(default=20, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True, help_text='Creation Date and Time', verbose_name='Creation Date and Time')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
