# Generated by Django 4.2.10 on 2024-02-11 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0003_userproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproduct',
            name='user',
        ),
        migrations.AddField(
            model_name='userproduct',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
