# Generated by Django 4.2.10 on 2024-02-12 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_userproduct_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='customer_country',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='customer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='StripeCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_link', models.CharField(max_length=100)),
                ('subscription_id', models.CharField(max_length=100)),
                ('currency_used', models.CharField(max_length=3)),
                ('transaction_id', models.CharField(max_length=264)),
                ('invoice_id', models.CharField(max_length=264)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payment.stripecustomer')),
            ],
        ),
    ]
