# Generated by Django 4.2.10 on 2024-02-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_stripecustomer_customer_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecheckout',
            name='raw_data',
            field=models.JSONField(default={}),
        ),
    ]
