# Generated by Django 4.2.10 on 2024-02-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_userproduct_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecheckout',
            name='raw_data',
            field=models.JSONField(default=dict),
        ),
    ]
