# Generated by Django 4.2.10 on 2024-02-19 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('price_id', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_type', models.CharField(blank=True, choices=[('mn', 'Monthly'), ('yr', 'Yearly'), ('wk', 'Weekly')], max_length=2, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('limit', models.PositiveIntegerField(blank=True, default=20, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True, help_text='Creation Date and Time', verbose_name='Creation Date and Time')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='Last Update of Date and Time', verbose_name='Last Update of Date and Time')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ManyToManyField(through='subscription.UserSubscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
