# Generated by Django 5.0.1 on 2024-01-27 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_properties', '0002_alter_userprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreceptionsetting',
            options={'verbose_name': '90_Email Reception Settings', 'verbose_name_plural': '90_Email Reception Settings'},
        ),
        migrations.AlterField(
            model_name='userreceptionsetting',
            name='is_receive_all',
            field=models.BooleanField(default=True, verbose_name='Receive All Notifications'),
        ),
        migrations.AlterField(
            model_name='userreceptionsetting',
            name='is_receive_important_only',
            field=models.BooleanField(default=False, verbose_name='Receive Only Important Notifications'),
        ),
        migrations.AlterField(
            model_name='userreceptionsetting',
            name='unique_account_id',
            field=models.OneToOneField(help_text='Associated account ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='related_user_reception_setting_unique_account_id', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
