# Generated by Django 5.0.1 on 2024-01-27 23:27

import common.scripts.custom_validaters
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_properties', '0003_alter_userreceptionsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(default='Enter Name Here', help_text='Alphanumeric, up to 25 characters in length', max_length=25, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), common.scripts.custom_validaters.validate_bad_id_name_words], verbose_name='Display Name'),
        ),
    ]
