# Generated by Django 5.0.1 on 2024-01-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_room_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.SlugField(default='f0308530b81748e29ff65b00744bf00f', unique=True, verbose_name='ルームID'),
        ),
    ]
