# Generated by Django 5.0.1 on 2024-01-27 22:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_room_room_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Message List', 'verbose_name_plural': 'Message List'},
        ),
        migrations.AlterField(
            model_name='message',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation Date and Time', verbose_name='Creation Date and Time'),
        ),
        migrations.AlterField(
            model_name='message',
            name='llm_response',
            field=models.TextField(blank=True, null=True, verbose_name='LLM Response'),
        ),
        migrations.AlterField(
            model_name='message',
            name='response_info',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Information'),
        ),
        migrations.AlterField(
            model_name='message',
            name='room_id',
            field=models.ForeignKey(help_text='Associated Room ID', on_delete=django.db.models.deletion.CASCADE, related_name='related_message_model_room_id', to='chat.room', verbose_name='Room ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_message',
            field=models.TextField(blank=True, null=True, verbose_name='User Message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_settings',
            field=models.TextField(blank=True, null=True, verbose_name="User's LLM Settings"),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.SlugField(default='07eae8d81d2e4738a11cdf55288cdc03', unique=True, verbose_name='ルームID'),
        ),
    ]
