# Generated by Django 5.0.1 on 2024-01-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_message_options_alter_message_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.SlugField(default='805ef5e442a14ed2964bfab3c72626ee', unique=True, verbose_name='ルームID'),
        ),
    ]
