# Generated by Django 5.0.1 on 2024-01-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_room_options_alter_roomsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.SlugField(default='f24f3ebb26f940fa937cdf0c3b17f21e', unique=True, verbose_name='Room ID'),
        ),
    ]
