# Generated by Django 5.0.1 on 2024-01-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_room_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.SlugField(default='c0b1a2352ca74a7ab58d681be061960d', unique=True, verbose_name='Room ID'),
        ),
    ]
