# Generated by Django 4.2.10 on 2024-02-09 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_room_room_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_id', models.CharField(max_length=200)),
                ('default', models.BooleanField(default=False)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Deletion Time of a Thread/Room', null=True, verbose_name='Deletion Date and Time'),
        ),
        migrations.AddField(
            model_name='room',
            name='expired_at',
            field=models.DateTimeField(blank=True, help_text='Expiration Time of a Thread/Room', null=True, verbose_name='Expiration Date and Time'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.SlugField(default='d13ab0c7b1f14bf1bfc4d178a6a5d651', unique=True, verbose_name='Room ID'),
        ),
        migrations.CreateModel(
            name='MessageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=20400, verbose_name='Image URL of a Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(help_text='Image for any Message', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chat.message')),
            ],
            options={
                'verbose_name': 'Message Images',
                'verbose_name_plural': 'Message Images',
                'db_table': 'message_image_model',
            },
        ),
        migrations.CreateModel(
            name='AssistantFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=200)),
                ('endpoint', models.URLField()),
                ('openapi_schema', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('assistant', models.ManyToManyField(to='chat.assistant')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='assistant_used',
            field=models.ForeignKey(help_text='Assistant Getting used in a Room', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.assistant', verbose_name='Assistant'),
        ),
    ]
