# Generated by Django 4.2.10 on 2024-02-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_room_gpt_thread_id_alter_room_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.SlugField(default='82ce34b7cff242cd86a10d732182ed42', unique=True, verbose_name='Room ID'),
        ),
    ]
