# Generated by Django 4.2.10 on 2024-02-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_alter_room_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.SlugField(default='6bd7048f195845129bb1428b3d767c78', unique=True, verbose_name='Room ID'),
        ),
    ]
