# Generated by Django 4.2.10 on 2024-02-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_alter_room_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.SlugField(default='7be77ae0ddd447658cb6c3b13159bb5a', unique=True, verbose_name='Room ID'),
        ),
    ]
