# Generated by Django 4.2.10 on 2024-02-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_alter_room_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.SlugField(default='15e7df01304d4fa498461635c35ba82c', unique=True, verbose_name='Room ID'),
        ),
    ]
