# Generated by Django 4.2.10 on 2024-02-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_alter_room_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.SlugField(default='2ed5df8ed7ca472eb4a0f065d53a5abe', unique=True, verbose_name='Room ID'),
        ),
    ]
