# Generated by Django 4.2.10 on 2024-02-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_alter_room_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.SlugField(default='ae3fcf47d17b48abb8e6c7b018299320', unique=True, verbose_name='Room ID'),
        ),
    ]
