# Generated by Django 4.2.10 on 2024-02-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_remove_messageimage_image_url_messageimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageimage',
            name='image',
        ),
        migrations.AddField(
            model_name='messageimage',
            name='image_url',
            field=models.CharField(default=1, max_length=20400, verbose_name='Image URL of a Message'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.SlugField(default='e209f2eb9c3a473db8dd0042e4654f64', unique=True, verbose_name='Room ID'),
        ),
    ]
