# Generated by Django 4.2.10 on 2024-02-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0027_remove_messageimage_image_messageimage_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.SlugField(default='296000036c25433c930919a2535b6034', unique=True, verbose_name='Room ID'),
        ),
    ]
